### PR TITLE
link to beta Hello Mochi procedure

### PR DESCRIPTION
**Pull request by carns**

### CODE REVIEW

**Comment by mdorier** [comment]
Could we put the content of the PDF on the readthedocs? (otherwise it's one more place to update in the future if something changes).

**Comment by carns** [comment]
Yeah, that makes sense, if you are comfortable with the content.

Do you have a suggestion on how to format the tables that are in the document in Sphinx?  They don't have to be tables necessarily, as long as it is something that  makes them stand out a little bit.  I'll look around some too.

**Comment by mdorier** [comment]
I don't think I have done tables in sphinx, so far.

**Comment by carns** [comment]
Ok, I just pushed another commit that puts them it in the repo directly as an rst document.  Can you check it out and see if that looks Ok @mdorier ?

**Comment by carns** [comment]
The PR check failure looks like a download error (i.e., bad luck) unrelated to my changes.  If the PR looks ok then I think we can just kick it to run again.

**Pull request merged**
